### PR TITLE
chore(source-scan): fix docker hello-world, add `--rm` flag to keep containers' slate clean

### PR DESCRIPTION
**Pull request by dj8yfo**
this helps one to avoid situation like the following

```bash
> docker ps -a
CONTAINER ID   IMAGE          COMMAND     CREATED         STATUS                     PORTS     NAMES
beebc6fabd59   hello-world    "/hello"    2 minutes ago   Exited (0) 2 minutes ago             thirsty_khayyam
b59f3a296253   hello-world    "/hello"    2 minutes ago   Exited (0) 2 minutes ago             nostalgic_proskuriakova
bf65bdf66e2d   hello-world    "/hello"    2 minutes ago   Exited (0) 2 minutes ago             elastic_raman
df77872a4e83   hello-world    "/hello"    2 minutes ago   Exited (0) 2 minutes ago             condescending_lovelace
7b5c5d675f4d   hello-world    "/hello"    4 hours ago     Exited (0) 4 hours ago               clever_davinci
baa7ed21d5a3   hello-world    "/hello"    4 hours ago     Exited (0) 4 hours ago               competent_noether
5f3f8b4ef47f   hello-world    "/hello"    6 hours ago     Exited (0) 6 hours ago               quirky_robinson
b3af2f69f0ce   hello-world    "/hello"    6 hours ago     Exited (0) 6 hours ago               peaceful_montalcini
7474b6b9a63e   hello-world    "/hello"    6 hours ago     Exited (0) 6 hours ago               gifted_ishizaka
8c1649c953bc   hello-world    "/hello"    7 hours ago     Exited (0) 7 hours ago               charming_curie
7671ebcf8b03   hello-world    "/hello"    7 hours ago     Exited (0) 7 hours ago               laughing_feynman
6bd65c95a1dc   hello-world    "/hello"    7 hours ago     Exited (0) 7 hours ago               blissful_williamson
35bc610101f1   hello-world    "/hello"    9 hours ago     Exited (0) 9 hours ago               sweet_turing
dcf9ff8002c2   hello-world    "/hello"    9 hours ago     Exited (0) 9 hours ago               tender_swartz
22938edbffa6   hello-world    "/hello"    9 hours ago     Exited (0) 9 hours ago               competent_goldstine
bb516160ad89   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                cranky_agnesi
133fe7e8ac35   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                clever_tu
ca2a73d83730   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                musing_matsumoto
4d2c07333f9a   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                intelligent_goodall
fb487ec0bd7d   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                admiring_pasteur
c6aa19bf78ec   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                vigilant_kalam
053027d416c1   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                epic_cray
4d54480f729c   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                peaceful_hertz
3a85cc2defc1   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                jovial_volhard
4d5ed4cb065a   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                determined_swirles
0d242e9e4e0f   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                dazzling_leakey
5025e729ed24   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                dazzling_bell
4b33b8e96cf6   hello-world    "/hello"    2 days ago      Exited (0) 2 days ago                festive_carson
4007c7ddb5b1   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                intelligent_johnson
208c6d6c3740   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                nifty_nightingale
462aa5bcec78   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                funny_heyrovsky
b65f7f4cec2a   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                musing_ganguly
225c621e7e79   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                objective_feynman
373b6e3c2364   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                stupefied_babbage
a419d742019a   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                priceless_euler
572a17618bfa   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                infallible_golick
05a5ffbff01f   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                condescending_roentgen
21ea755e137f   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                sharp_ishizaka
ffab88a8994c   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                gallant_archimedes
444255a624c4   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                suspicious_aryabhata
731ccc251f90   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                clever_pasteur
a0e7f67c0a58   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                boring_maxwell
06c2962c9259   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                sleepy_faraday
219061a4243c   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                hungry_hopper
0d75ae75281a   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                mystifying_meitner
902373262fcd   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                relaxed_morse
a62276ea2e89   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                vigilant_beaver
dd2bdbd600ec   hello-world    "/hello"    6 days ago      Exited (0) 6 days ago                charming_benz
d68930274c6f   bab5e95c6a09   "/bin/sh"   9 days ago      Exited (0) 9 days ago                suspicious_banzai
d7db5deb2d5d   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                intelligent_torvalds
dffbaa95d563   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                reverent_hellman
0d79b8720dc2   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                admiring_morse
a04d69f5fa79   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                naughty_mclean
198f30a8e732   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                xenodochial_pascal
488151c187ed   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                musing_poitras
4454fdcc3600   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                upbeat_ardinghelli
03ee5588b30d   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                exciting_darwin
b8557213f74a   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                great_aryabhata
675769ea7b7c   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                wonderful_hopper
e176ddf9e03a   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                hungry_hugle
a56b30bf58c5   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                sleepy_brown
413bdca80e6c   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                thirsty_brahmagupta
8995a9ed4762   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                confident_archimedes
e9b6dd3f98d9   hello-world    "/hello"    9 days ago      Exited (0) 9 days ago                vigorous_bassi
0b8c84b95e30   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               clever_hermann
9d4485f16efa   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               sleepy_feistel
d359d1121992   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               pensive_lichterman
85fe0b3fc427   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               hardcore_lichterman
d8f2a662b10a   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               pedantic_robinson
1ebe283d7350   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               upbeat_visvesvaraya
c3ebdc1eb21b   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               nostalgic_germain
fadaba548378   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               relaxed_carver
859b9e2c23d4   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               tender_germain
a66dd58e2c40   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               crazy_golick
108397933ba9   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               vibrant_hypatia
7695d90b4e55   hello-world    "/hello"    10 days ago     Exited (0) 10 days ago               happy_pare

```

### CODE REVIEW

**Comment by dj8yfo** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
@dj8yfo Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Great job! Usain Bolt jealous of your results!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/dj8yfo?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/dj8yfo?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/dj8yfo)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/dj8yfo)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Review by frol — APPROVED** [review]

**Comment by frol** [comment]
@race-of-sloths score 1

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@frol, thank you for scoring this pull request in the Race of Sloths!

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 1!
You have received 10 Sloth points for this contribution

**Pull request merged**
