### PR TITLE
Fix/ci issues

### PR DESCRIPTION
**Pull request by ghimire007**
Ci issues related to audit ,clippy and tests fixed

### CODE REVIEW

**Comment by ghimire007** [comment]
CI isses  fixed

**Review by frol — CHANGES_REQUESTED** [review]
@ghimire007 Please, update MSRV in Cargo.toml to the minimum required one and make sure CI is green

**Comment by ghimire007** [comment]
@frol MSRV in cargo.toml updated

**Comment by frol** [comment]
@ghimire007 Is it really the minimum required version to compile cargo-near?

**Comment by ghimire007** [comment]
@frol 1.60.0 is seems to be minimum version required to compile. Cargo.toml now has version 1.60.0 .

**Review by frol — APPROVED** [review]

**Pull request merged**
