### PR TITLE
alt build stages style

### PR DESCRIPTION
**Pull request by miraclx**
@itegulov, what do you think of this styling pattern?

CleanShot 2022-10-15 at 11 44 51@2x

### CODE REVIEW

**Comment by itegulov** [comment]
Yoo, looks clean. I guess we don't need to pad the cargo output as much then. And also would be nice to incorporate the last lines with output files in the style somehow too :thinking:

**Comment by miraclx** [comment]
Yeah, didn't want to have to push the text farther right. Another thing I noticed is when there's a cargo error, it doesn't have any colors. And for some reason, it's written to stdout instead of stderr. So it doesn't have the indented scoping that the build process has.

**Comment by itegulov** [comment]
> It's because of --message-format json, got it.

Yeah, I could not find a way to combine JSON message format with colored output.

**Comment by miraclx** [comment]
> Yeah, I could not find a way to combine JSON message format with colored output.

Seems to be the current situation, anyway, the error example in #65 isn't so bad either.

**Pull request merged**
